name: Pipe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests-e2e-selenium:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - uses: browser-actions/setup-chrome@latest
    - name: Install chrome
      run: chrome --version
  
    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: '116.0.5845.96'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Build with Maven
      run: mvn install -DskipTests

    - name: Running test with chrome
      run: mvn test -DBROWSER=chrome-headless