name: Pipe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - uses: abhi1693/setup-browser@v0.3.4
      with:
        browser: chrome
        version: latest
  
    - name: Build with Maven
      run: mvn install -DskipTests

    - name: Running test with chrome
      run: mvn test -DBROWSER=chrome-headless