name: Pipe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests-e2e-selenium:
    runs-on: ubuntu-latest

    steps:
    - uses: com.saucedemo.actions/checkout@v2
    - name: Set up JDK 11
      uses: com.saucedemo.actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - uses: browser-com.saucedemo.actions/setup-chrome@latest
    - run: chrome --version

    - name: Build with Maven
      run: mvn install -DskipTests

    - name: Running test with chrome
      run: mvn test -DBROWSER=chrome-headless

    - name: Get Allure History
      uses: com.saucedemo.actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-com.saucedemo.pages
        path: gh-com.saucedemo.pages

    - name: Action From Marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: ./allure-results
        gh_pages: gh-com.saucedemo.pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/com.saucedemo.actions-gh-com.saucedemo.pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-com.saucedemo.pages
        PUBLISH_DIR: allure-history